<a href="https://colab.research.google.com/github/recoderbin/Process/blob/main/%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

dict_items([('강감찬', '010-2222-1111'), ('이순신', '010-1111-3333')])

In [ ]:
import numpy as np
darray = np.array([[1,3,5,7,9],[2,4,6,8,10]])
darray

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [ ]:
d10 = darray.reshape(10, )
d10

array([ 1,  3,  5,  7,  9,  2,  4,  6,  8, 10])

In [ ]:
zero = np.zeros((2, 5))
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
one = np.ones((2, 5))
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])